# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NativeAddRNProject' do
     # 取决于你的工程如何组织，你的node_modules文件夹可能会在别的地方。
     # 请将:path后面的内容修改为正确的路径（一定要确保正确～～）。
     pod 'React', :path => './ReactComponent/node_modules/react-native', :subspecs => [
     'Core',
     'CxxBridge', # 如果RN版本 >= 0.47则加入此行
     'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
     'RCTText',
     'RCTNetwork',
     'RCTWebSocket', # 调试功能需要此模块
     'RCTAnimation', # FlatList和原生动画功能需要此模块
     'RCTPushNotification',
     'RCTSettings',
     'RCTText',
     # 在这里继续添加你所需要的其他RN模块
     ]
     # 如果你的RN版本 >= 0.42.0，则加入下面这行
     pod 'yoga', :path => './ReactComponent/node_modules/react-native/ReactCommon/yoga'

     # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
     pod 'DoubleConversion', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
     pod 'glog', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/glog.podspec'
     pod 'Folly', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/Folly.podspec'
  target 'NativeAddRNProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeAddRNProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
